# Generated by Django 5.1.2 on 2024-10-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubissues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='repo_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
