# Generated by Django 5.1.2 on 2024-10-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubissues', '0003_issue_closed_at_repository_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closed_by',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='comments_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_by',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='issue',
            name='milestone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, null=True)),
                ('user', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_association', models.CharField(blank=True, max_length=50, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='githubissues.issue')),
            ],
        ),
    ]
