# Generated by Django 5.1.2 on 2024-10-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubissues', '0007_rename_task_id_issue_issue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null='true'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='has_issues',
            field=models.BooleanField(default=False, null='true'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.CharField(default='Unknown', max_length=250, null='true'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.CharField(max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='pushed_at',
            field=models.DateTimeField(auto_now_add=True, null='true'),
        ),
    ]
